Add libgtk3 dependency to puppeteer role & upgrade puppeteer
We observed that Time Machine stopped working, and went to find some
errors in the logs.

We saw this error:

```
java.lang.RuntimeException: External process failed with error output: (node:9347) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome! /node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/node_modules/puppeteer/lib/Launcher.js:339:14) at Interface.helper.addEventListener
```

Which prompted us to see if updating the version of libgtk-3-0 by ssh-ing
directly onto the time machine box would get time machine up and running
again. It did! So we'll need to update libgtk-3-0 as a puppeteer dependency.

We were also curious if Time Machine would still work with a puppeteer update, so
we updated puppeteer with npm on the Time Machine box in prod after updating libgtk-3-0
and this works, so we also bump the puppeteer version here.

Co-authored-by: Simone Smith  <simone.smith@guardian.co.uk>