Ensure credentials update
The static provider doesn't update credentials, which was resulting
in this error:

software.amazon.awssdk.services.dynamodb.model.DynamoDbException: The security token included in the request is expired